package Pertemuan14;

//@author AZZAM FARRAS RUSLANI
public class Percobaan12 extends Exception {

    private final String Teks;

    Percobaan12(String s) {
        Teks = "Exception generated by: " + s;
        System.out.println(Teks);
    }
}

class Eksepsi {

    static void tampil(String s) throws Exception {
        System.out.println("Tampil");
        if (s.equals("amir")) {
            throw new Percobaan12(s);
        }
        System.out.println("OK!");
    }

    public static void main(String[] args) throws Exception {
        try {
            tampil("ali");
            tampil("amir");
        } catch (Percobaan12 ex) {
            System.out.println("Tangkap:" + ex);
        }
    }
}
